#!/usr/bin/python

import os
import sys
import time

def record(filename):
    os.system('/usr/local/bin/bto_advanced_USBIR_cmd -r')
    time.sleep(3)
    os.system('/usr/local/bin/bto_advanced_USBIR_cmd -s')
    os.system('/usr/local/bin/bto_advanced_USBIR_cmd -g | tee ' + filename)

if __name__ == '__main__':
    argv = sys.argv
    if len(argv) > 1:
        filename = argv[1]
    else:
        filename = 'ir.txt'

    record(filename)
